#!/usr/bin/env node
/*
 * Preprocesses the exercises dataset into app-ready assets:
 *  - src/data/exercises.json   (slim: only fields the app needs, TR+EN steps)
 *  - src/data/gifMap.ts        (exercise id -> require(gif))
 *  - src/data/imgMap.ts        (exercise id -> require(thumbnail))
 *  - assets/exercises/gifs/    (copied gifs)
 *  - assets/exercises/thumbs/  (copied thumbnails)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DATASET = path.join(ROOT, 'dataset');
const APP = path.join(ROOT, 'app');
const GIF_OUT = path.join(APP, 'assets', 'exercises', 'gifs');
const IMG_OUT = path.join(APP, 'assets', 'exercises', 'thumbs');
const DATA_OUT = path.join(APP, 'src', 'data');

for (const d of [GIF_OUT, IMG_OUT, DATA_OUT]) fs.mkdirSync(d, { recursive: true });

const raw = JSON.parse(fs.readFileSync(path.join(DATASET, 'data', 'exercises.json'), 'utf8'));
console.log(`Loaded ${raw.length} exercises`);

const slim = [];
const gifLines = [];
const imgLines = [];
let missingMedia = 0;

for (const e of raw) {
  const gifName = path.basename(e.gif_url); // videos/0001-2gPfomN.gif
  const imgName = path.basename(e.image);
  const gifSrc = path.join(DATASET, 'videos', gifName);
  const imgSrc = path.join(DATASET, 'images', imgName);

  if (!fs.existsSync(gifSrc) || !fs.existsSync(imgSrc)) {
    missingMedia++;
    console.warn(`missing media for ${e.id} ${e.name}`);
    continue;
  }

  fs.copyFileSync(gifSrc, path.join(GIF_OUT, gifName));
  fs.copyFileSync(imgSrc, path.join(IMG_OUT, imgName));

  slim.push({
    id: e.id,
    name: e.name,
    bodyPart: e.body_part,
    equipment: e.equipment,
    target: e.target,
    muscleGroup: e.muscle_group,
    secondaryMuscles: e.secondary_muscles || [],
    gif: gifName,
    img: imgName,
    steps: {
      tr: e.instruction_steps?.tr?.length ? e.instruction_steps.tr : e.instruction_steps?.en || [],
      en: e.instruction_steps?.en || [],
    },
  });

  gifLines.push(`  "${e.id}": require("../../assets/exercises/gifs/${gifName}"),`);
  imgLines.push(`  "${e.id}": require("../../assets/exercises/thumbs/${imgName}"),`);
}

fs.writeFileSync(path.join(DATA_OUT, 'exercises.json'), JSON.stringify(slim));

const header = `// GENERATED by scripts/prepare-data.js — do not edit
// eslint-disable-next-line @typescript-eslint/no-var-requires
`;
fs.writeFileSync(
  path.join(DATA_OUT, 'gifMap.ts'),
  `${header}const gifs: Record<string, number> = {\n${gifLines.join('\n')}\n};\nexport default gifs;\n`
);
fs.writeFileSync(
  path.join(DATA_OUT, 'imgMap.ts'),
  `${header}const images: Record<string, number> = {\n${imgLines.join('\n')}\n};\nexport default images;\n`
);

const sizeMB = (fs.statSync(path.join(DATA_OUT, 'exercises.json')).size / 1e6).toFixed(1);
console.log(`Wrote ${slim.length} exercises (${sizeMB}MB json). Missing media: ${missingMedia}`);
